from game import Move

'''
each code/id is unique number that represents an action
1-7: are movements that need to be parsed in real time

90000-98811: are all predefined wall placements that can be used in the game directly (some are illegal, but that is handled in the game logic)
9 - every code starts with a 9 as it needs to be an integer and board locations range from 0-8 so 9 is a safe number to use
00 - the first two digits represent the row and column of the wall
the next digit 0 or 1 represents the orientation of the wall, 0 is horizontal, 1 is vertical
the next digit 0 or 1 represents the colour of the wall, 0 is white, 1 is black
i.e. 90000 is a white placing horizontal wall at a9 and 90001 is a black placing horizontal wall at a9 (these are illegal moves :})
'''

action_lookup = {
    1 : 'up',
    2 : 'down',
    3 : 'left',
    4 : 'right',
    5 : 'jump left',
    6 : 'jump right',
    7 : 'jump straight',
    90000 : Move('white', 'a9', None, 'place', None, None, 'horizontal'),
    90001 : Move('black', 'a9', None, 'place', None, None, 'horizontal'),
    90010 : Move('white', 'a9', None, 'place', None, None, 'vertical'),
    90011 : Move('black', 'a9', None, 'place', None, None, 'vertical'),
    90100 : Move('white', 'b9', None, 'place', None, None, 'horizontal'),
    90101 : Move('black', 'b9', None, 'place', None, None, 'horizontal'),
    90110 : Move('white', 'b9', None, 'place', None, None, 'vertical'),
    90111 : Move('black', 'b9', None, 'place', None, None, 'vertical'),
    90200 : Move('white', 'c9', None, 'place', None, None, 'horizontal'),
    90201 : Move('black', 'c9', None, 'place', None, None, 'horizontal'),
    90210 : Move('white', 'c9', None, 'place', None, None, 'vertical'),
    90211 : Move('black', 'c9', None, 'place', None, None, 'vertical'),
    90300 : Move('white', 'd9', None, 'place', None, None, 'horizontal'),
    90301 : Move('black', 'd9', None, 'place', None, None, 'horizontal'),
    90310 : Move('white', 'd9', None, 'place', None, None, 'vertical'),
    90311 : Move('black', 'd9', None, 'place', None, None, 'vertical'),
    90400 : Move('white', 'e9', None, 'place', None, None, 'horizontal'),
    90401 : Move('black', 'e9', None, 'place', None, None, 'horizontal'),
    90410 : Move('white', 'e9', None, 'place', None, None, 'vertical'),
    90411 : Move('black', 'e9', None, 'place', None, None, 'vertical'),
    90500 : Move('white', 'f9', None, 'place', None, None, 'horizontal'),
    90501 : Move('black', 'f9', None, 'place', None, None, 'horizontal'),
    90510 : Move('white', 'f9', None, 'place', None, None, 'vertical'),
    90511 : Move('black', 'f9', None, 'place', None, None, 'vertical'),
    90600 : Move('white', 'g9', None, 'place', None, None, 'horizontal'),
    90601 : Move('black', 'g9', None, 'place', None, None, 'horizontal'),
    90610 : Move('white', 'g9', None, 'place', None, None, 'vertical'),
    90611 : Move('black', 'g9', None, 'place', None, None, 'vertical'),
    90700 : Move('white', 'h9', None, 'place', None, None, 'horizontal'),
    90701 : Move('black', 'h9', None, 'place', None, None, 'horizontal'),
    90710 : Move('white', 'h9', None, 'place', None, None, 'vertical'),
    90711 : Move('black', 'h9', None, 'place', None, None, 'vertical'),
    90800 : Move('white', 'i9', None, 'place', None, None, 'horizontal'),
    90801 : Move('black', 'i9', None, 'place', None, None, 'horizontal'),
    90810 : Move('white', 'i9', None, 'place', None, None, 'vertical'),
    90811 : Move('black', 'i9', None, 'place', None, None, 'vertical'),
    91000 : Move('white', 'a8', None, 'place', None, None, 'horizontal'),
    91001 : Move('black', 'a8', None, 'place', None, None, 'horizontal'),
    91010 : Move('white', 'a8', None, 'place', None, None, 'vertical'),
    91011 : Move('black', 'a8', None, 'place', None, None, 'vertical'),
    91100 : Move('white', 'b8', None, 'place', None, None, 'horizontal'),
    91101 : Move('black', 'b8', None, 'place', None, None, 'horizontal'),
    91110 : Move('white', 'b8', None, 'place', None, None, 'vertical'),
    91111 : Move('black', 'b8', None, 'place', None, None, 'vertical'),
    91200 : Move('white', 'c8', None, 'place', None, None, 'horizontal'),
    91201 : Move('black', 'c8', None, 'place', None, None, 'horizontal'),
    91210 : Move('white', 'c8', None, 'place', None, None, 'vertical'),
    91211 : Move('black', 'c8', None, 'place', None, None, 'vertical'),
    91300 : Move('white', 'd8', None, 'place', None, None, 'horizontal'),
    91301 : Move('black', 'd8', None, 'place', None, None, 'horizontal'),
    91310 : Move('white', 'd8', None, 'place', None, None, 'vertical'),
    91311 : Move('black', 'd8', None, 'place', None, None, 'vertical'),
    91400 : Move('white', 'e8', None, 'place', None, None, 'horizontal'),
    91401 : Move('black', 'e8', None, 'place', None, None, 'horizontal'),
    91410 : Move('white', 'e8', None, 'place', None, None, 'vertical'),
    91411 : Move('black', 'e8', None, 'place', None, None, 'vertical'),
    91500 : Move('white', 'f8', None, 'place', None, None, 'horizontal'),
    91501 : Move('black', 'f8', None, 'place', None, None, 'horizontal'),
    91510 : Move('white', 'f8', None, 'place', None, None, 'vertical'),
    91511 : Move('black', 'f8', None, 'place', None, None, 'vertical'),
    91600 : Move('white', 'g8', None, 'place', None, None, 'horizontal'),
    91601 : Move('black', 'g8', None, 'place', None, None, 'horizontal'),
    91610 : Move('white', 'g8', None, 'place', None, None, 'vertical'),
    91611 : Move('black', 'g8', None, 'place', None, None, 'vertical'),
    91700 : Move('white', 'h8', None, 'place', None, None, 'horizontal'),
    91701 : Move('black', 'h8', None, 'place', None, None, 'horizontal'),
    91710 : Move('white', 'h8', None, 'place', None, None, 'vertical'),
    91711 : Move('black', 'h8', None, 'place', None, None, 'vertical'),
    91800 : Move('white', 'i8', None, 'place', None, None, 'horizontal'),
    91801 : Move('black', 'i8', None, 'place', None, None, 'horizontal'),
    91810 : Move('white', 'i8', None, 'place', None, None, 'vertical'),
    91811 : Move('black', 'i8', None, 'place', None, None, 'vertical'),
    92000 : Move('white', 'a7', None, 'place', None, None, 'horizontal'),
    92001 : Move('black', 'a7', None, 'place', None, None, 'horizontal'),
    92010 : Move('white', 'a7', None, 'place', None, None, 'vertical'),
    92011 : Move('black', 'a7', None, 'place', None, None, 'vertical'),
    92100 : Move('white', 'b7', None, 'place', None, None, 'horizontal'),
    92101 : Move('black', 'b7', None, 'place', None, None, 'horizontal'),
    92110 : Move('white', 'b7', None, 'place', None, None, 'vertical'),
    92111 : Move('black', 'b7', None, 'place', None, None, 'vertical'),
    92200 : Move('white', 'c7', None, 'place', None, None, 'horizontal'),
    92201 : Move('black', 'c7', None, 'place', None, None, 'horizontal'),
    92210 : Move('white', 'c7', None, 'place', None, None, 'vertical'),
    92211 : Move('black', 'c7', None, 'place', None, None, 'vertical'),
    92300 : Move('white', 'd7', None, 'place', None, None, 'horizontal'),
    92301 : Move('black', 'd7', None, 'place', None, None, 'horizontal'),
    92310 : Move('white', 'd7', None, 'place', None, None, 'vertical'),
    92311 : Move('black', 'd7', None, 'place', None, None, 'vertical'),
    92400 : Move('white', 'e7', None, 'place', None, None, 'horizontal'),
    92401 : Move('black', 'e7', None, 'place', None, None, 'horizontal'),
    92410 : Move('white', 'e7', None, 'place', None, None, 'vertical'),
    92411 : Move('black', 'e7', None, 'place', None, None, 'vertical'),
    92500 : Move('white', 'f7', None, 'place', None, None, 'horizontal'),
    92501 : Move('black', 'f7', None, 'place', None, None, 'horizontal'),
    92510 : Move('white', 'f7', None, 'place', None, None, 'vertical'),
    92511 : Move('black', 'f7', None, 'place', None, None, 'vertical'),
    92600 : Move('white', 'g7', None, 'place', None, None, 'horizontal'),
    92601 : Move('black', 'g7', None, 'place', None, None, 'horizontal'),
    92610 : Move('white', 'g7', None, 'place', None, None, 'vertical'),
    92611 : Move('black', 'g7', None, 'place', None, None, 'vertical'),
    92700 : Move('white', 'h7', None, 'place', None, None, 'horizontal'),
    92701 : Move('black', 'h7', None, 'place', None, None, 'horizontal'),
    92710 : Move('white', 'h7', None, 'place', None, None, 'vertical'),
    92711 : Move('black', 'h7', None, 'place', None, None, 'vertical'),
    92800 : Move('white', 'i7', None, 'place', None, None, 'horizontal'),
    92801 : Move('black', 'i7', None, 'place', None, None, 'horizontal'),
    92810 : Move('white', 'i7', None, 'place', None, None, 'vertical'),
    92811 : Move('black', 'i7', None, 'place', None, None, 'vertical'),
    93000 : Move('white', 'a6', None, 'place', None, None, 'horizontal'),
    93001 : Move('black', 'a6', None, 'place', None, None, 'horizontal'),
    93010 : Move('white', 'a6', None, 'place', None, None, 'vertical'),
    93011 : Move('black', 'a6', None, 'place', None, None, 'vertical'),
    93100 : Move('white', 'b6', None, 'place', None, None, 'horizontal'),
    93101 : Move('black', 'b6', None, 'place', None, None, 'horizontal'),
    93110 : Move('white', 'b6', None, 'place', None, None, 'vertical'),
    93111 : Move('black', 'b6', None, 'place', None, None, 'vertical'),
    93200 : Move('white', 'c6', None, 'place', None, None, 'horizontal'),
    93201 : Move('black', 'c6', None, 'place', None, None, 'horizontal'),
    93210 : Move('white', 'c6', None, 'place', None, None, 'vertical'),
    93211 : Move('black', 'c6', None, 'place', None, None, 'vertical'),
    93300 : Move('white', 'd6', None, 'place', None, None, 'horizontal'),
    93301 : Move('black', 'd6', None, 'place', None, None, 'horizontal'),
    93310 : Move('white', 'd6', None, 'place', None, None, 'vertical'),
    93311 : Move('black', 'd6', None, 'place', None, None, 'vertical'),
    93400 : Move('white', 'e6', None, 'place', None, None, 'horizontal'),
    93401 : Move('black', 'e6', None, 'place', None, None, 'horizontal'),
    93410 : Move('white', 'e6', None, 'place', None, None, 'vertical'),
    93411 : Move('black', 'e6', None, 'place', None, None, 'vertical'),
    93500 : Move('white', 'f6', None, 'place', None, None, 'horizontal'),
    93501 : Move('black', 'f6', None, 'place', None, None, 'horizontal'),
    93510 : Move('white', 'f6', None, 'place', None, None, 'vertical'),
    93511 : Move('black', 'f6', None, 'place', None, None, 'vertical'),
    93600 : Move('white', 'g6', None, 'place', None, None, 'horizontal'),
    93601 : Move('black', 'g6', None, 'place', None, None, 'horizontal'),
    93610 : Move('white', 'g6', None, 'place', None, None, 'vertical'),
    93611 : Move('black', 'g6', None, 'place', None, None, 'vertical'),
    93700 : Move('white', 'h6', None, 'place', None, None, 'horizontal'),
    93701 : Move('black', 'h6', None, 'place', None, None, 'horizontal'),
    93710 : Move('white', 'h6', None, 'place', None, None, 'vertical'),
    93711 : Move('black', 'h6', None, 'place', None, None, 'vertical'),
    93800 : Move('white', 'i6', None, 'place', None, None, 'horizontal'),
    93801 : Move('black', 'i6', None, 'place', None, None, 'horizontal'),
    93810 : Move('white', 'i6', None, 'place', None, None, 'vertical'),
    93811 : Move('black', 'i6', None, 'place', None, None, 'vertical'),
    94000 : Move('white', 'a5', None, 'place', None, None, 'horizontal'),
    94001 : Move('black', 'a5', None, 'place', None, None, 'horizontal'),
    94010 : Move('white', 'a5', None, 'place', None, None, 'vertical'),
    94011 : Move('black', 'a5', None, 'place', None, None, 'vertical'),
    94100 : Move('white', 'b5', None, 'place', None, None, 'horizontal'),
    94101 : Move('black', 'b5', None, 'place', None, None, 'horizontal'),
    94110 : Move('white', 'b5', None, 'place', None, None, 'vertical'),
    94111 : Move('black', 'b5', None, 'place', None, None, 'vertical'),
    94200 : Move('white', 'c5', None, 'place', None, None, 'horizontal'),
    94201 : Move('black', 'c5', None, 'place', None, None, 'horizontal'),
    94210 : Move('white', 'c5', None, 'place', None, None, 'vertical'),
    94211 : Move('black', 'c5', None, 'place', None, None, 'vertical'),
    94300 : Move('white', 'd5', None, 'place', None, None, 'horizontal'),
    94301 : Move('black', 'd5', None, 'place', None, None, 'horizontal'),
    94310 : Move('white', 'd5', None, 'place', None, None, 'vertical'),
    94311 : Move('black', 'd5', None, 'place', None, None, 'vertical'),
    94400 : Move('white', 'e5', None, 'place', None, None, 'horizontal'),
    94401 : Move('black', 'e5', None, 'place', None, None, 'horizontal'),
    94410 : Move('white', 'e5', None, 'place', None, None, 'vertical'),
    94411 : Move('black', 'e5', None, 'place', None, None, 'vertical'),
    94500 : Move('white', 'f5', None, 'place', None, None, 'horizontal'),
    94501 : Move('black', 'f5', None, 'place', None, None, 'horizontal'),
    94510 : Move('white', 'f5', None, 'place', None, None, 'vertical'),
    94511 : Move('black', 'f5', None, 'place', None, None, 'vertical'),
    94600 : Move('white', 'g5', None, 'place', None, None, 'horizontal'),
    94601 : Move('black', 'g5', None, 'place', None, None, 'horizontal'),
    94610 : Move('white', 'g5', None, 'place', None, None, 'vertical'),
    94611 : Move('black', 'g5', None, 'place', None, None, 'vertical'),
    94700 : Move('white', 'h5', None, 'place', None, None, 'horizontal'),
    94701 : Move('black', 'h5', None, 'place', None, None, 'horizontal'),
    94710 : Move('white', 'h5', None, 'place', None, None, 'vertical'),
    94711 : Move('black', 'h5', None, 'place', None, None, 'vertical'),
    94800 : Move('white', 'i5', None, 'place', None, None, 'horizontal'),
    94801 : Move('black', 'i5', None, 'place', None, None, 'horizontal'),
    94810 : Move('white', 'i5', None, 'place', None, None, 'vertical'),
    94811 : Move('black', 'i5', None, 'place', None, None, 'vertical'),
    95000 : Move('white', 'a4', None, 'place', None, None, 'horizontal'),
    95001 : Move('black', 'a4', None, 'place', None, None, 'horizontal'),
    95010 : Move('white', 'a4', None, 'place', None, None, 'vertical'),
    95011 : Move('black', 'a4', None, 'place', None, None, 'vertical'),
    95100 : Move('white', 'b4', None, 'place', None, None, 'horizontal'),
    95101 : Move('black', 'b4', None, 'place', None, None, 'horizontal'),
    95110 : Move('white', 'b4', None, 'place', None, None, 'vertical'),
    95111 : Move('black', 'b4', None, 'place', None, None, 'vertical'),
    95200 : Move('white', 'c4', None, 'place', None, None, 'horizontal'),
    95201 : Move('black', 'c4', None, 'place', None, None, 'horizontal'),
    95210 : Move('white', 'c4', None, 'place', None, None, 'vertical'),
    95211 : Move('black', 'c4', None, 'place', None, None, 'vertical'),
    95300 : Move('white', 'd4', None, 'place', None, None, 'horizontal'),
    95301 : Move('black', 'd4', None, 'place', None, None, 'horizontal'),
    95310 : Move('white', 'd4', None, 'place', None, None, 'vertical'),
    95311 : Move('black', 'd4', None, 'place', None, None, 'vertical'),
    95400 : Move('white', 'e4', None, 'place', None, None, 'horizontal'),
    95401 : Move('black', 'e4', None, 'place', None, None, 'horizontal'),
    95410 : Move('white', 'e4', None, 'place', None, None, 'vertical'),
    95411 : Move('black', 'e4', None, 'place', None, None, 'vertical'),
    95500 : Move('white', 'f4', None, 'place', None, None, 'horizontal'),
    95501 : Move('black', 'f4', None, 'place', None, None, 'horizontal'),
    95510 : Move('white', 'f4', None, 'place', None, None, 'vertical'),
    95511 : Move('black', 'f4', None, 'place', None, None, 'vertical'),
    95600 : Move('white', 'g4', None, 'place', None, None, 'horizontal'),
    95601 : Move('black', 'g4', None, 'place', None, None, 'horizontal'),
    95610 : Move('white', 'g4', None, 'place', None, None, 'vertical'),
    95611 : Move('black', 'g4', None, 'place', None, None, 'vertical'),
    95700 : Move('white', 'h4', None, 'place', None, None, 'horizontal'),
    95701 : Move('black', 'h4', None, 'place', None, None, 'horizontal'),
    95710 : Move('white', 'h4', None, 'place', None, None, 'vertical'),
    95711 : Move('black', 'h4', None, 'place', None, None, 'vertical'),
    95800 : Move('white', 'i4', None, 'place', None, None, 'horizontal'),
    95801 : Move('black', 'i4', None, 'place', None, None, 'horizontal'),
    95810 : Move('white', 'i4', None, 'place', None, None, 'vertical'),
    95811 : Move('black', 'i4', None, 'place', None, None, 'vertical'),
    96000 : Move('white', 'a3', None, 'place', None, None, 'horizontal'),
    96001 : Move('black', 'a3', None, 'place', None, None, 'horizontal'),
    96010 : Move('white', 'a3', None, 'place', None, None, 'vertical'),
    96011 : Move('black', 'a3', None, 'place', None, None, 'vertical'),
    96100 : Move('white', 'b3', None, 'place', None, None, 'horizontal'),
    96101 : Move('black', 'b3', None, 'place', None, None, 'horizontal'),
    96110 : Move('white', 'b3', None, 'place', None, None, 'vertical'),
    96111 : Move('black', 'b3', None, 'place', None, None, 'vertical'),
    96200 : Move('white', 'c3', None, 'place', None, None, 'horizontal'),
    96201 : Move('black', 'c3', None, 'place', None, None, 'horizontal'),
    96210 : Move('white', 'c3', None, 'place', None, None, 'vertical'),
    96211 : Move('black', 'c3', None, 'place', None, None, 'vertical'),
    96300 : Move('white', 'd3', None, 'place', None, None, 'horizontal'),
    96301 : Move('black', 'd3', None, 'place', None, None, 'horizontal'),
    96310 : Move('white', 'd3', None, 'place', None, None, 'vertical'),
    96311 : Move('black', 'd3', None, 'place', None, None, 'vertical'),
    96400 : Move('white', 'e3', None, 'place', None, None, 'horizontal'),
    96401 : Move('black', 'e3', None, 'place', None, None, 'horizontal'),
    96410 : Move('white', 'e3', None, 'place', None, None, 'vertical'),
    96411 : Move('black', 'e3', None, 'place', None, None, 'vertical'),
    96500 : Move('white', 'f3', None, 'place', None, None, 'horizontal'),
    96501 : Move('black', 'f3', None, 'place', None, None, 'horizontal'),
    96510 : Move('white', 'f3', None, 'place', None, None, 'vertical'),
    96511 : Move('black', 'f3', None, 'place', None, None, 'vertical'),
    96600 : Move('white', 'g3', None, 'place', None, None, 'horizontal'),
    96601 : Move('black', 'g3', None, 'place', None, None, 'horizontal'),
    96610 : Move('white', 'g3', None, 'place', None, None, 'vertical'),
    96611 : Move('black', 'g3', None, 'place', None, None, 'vertical'),
    96700 : Move('white', 'h3', None, 'place', None, None, 'horizontal'),
    96701 : Move('black', 'h3', None, 'place', None, None, 'horizontal'),
    96710 : Move('white', 'h3', None, 'place', None, None, 'vertical'),
    96711 : Move('black', 'h3', None, 'place', None, None, 'vertical'),
    96800 : Move('white', 'i3', None, 'place', None, None, 'horizontal'),
    96801 : Move('black', 'i3', None, 'place', None, None, 'horizontal'),
    96810 : Move('white', 'i3', None, 'place', None, None, 'vertical'),
    96811 : Move('black', 'i3', None, 'place', None, None, 'vertical'),
    97000 : Move('white', 'a2', None, 'place', None, None, 'horizontal'),
    97001 : Move('black', 'a2', None, 'place', None, None, 'horizontal'),
    97010 : Move('white', 'a2', None, 'place', None, None, 'vertical'),
    97011 : Move('black', 'a2', None, 'place', None, None, 'vertical'),
    97100 : Move('white', 'b2', None, 'place', None, None, 'horizontal'),
    97101 : Move('black', 'b2', None, 'place', None, None, 'horizontal'),
    97110 : Move('white', 'b2', None, 'place', None, None, 'vertical'),
    97111 : Move('black', 'b2', None, 'place', None, None, 'vertical'),
    97200 : Move('white', 'c2', None, 'place', None, None, 'horizontal'),
    97201 : Move('black', 'c2', None, 'place', None, None, 'horizontal'),
    97210 : Move('white', 'c2', None, 'place', None, None, 'vertical'),
    97211 : Move('black', 'c2', None, 'place', None, None, 'vertical'),
    97300 : Move('white', 'd2', None, 'place', None, None, 'horizontal'),
    97301 : Move('black', 'd2', None, 'place', None, None, 'horizontal'),
    97310 : Move('white', 'd2', None, 'place', None, None, 'vertical'),
    97311 : Move('black', 'd2', None, 'place', None, None, 'vertical'),
    97400 : Move('white', 'e2', None, 'place', None, None, 'horizontal'),
    97401 : Move('black', 'e2', None, 'place', None, None, 'horizontal'),
    97410 : Move('white', 'e2', None, 'place', None, None, 'vertical'),
    97411 : Move('black', 'e2', None, 'place', None, None, 'vertical'),
    97500 : Move('white', 'f2', None, 'place', None, None, 'horizontal'),
    97501 : Move('black', 'f2', None, 'place', None, None, 'horizontal'),
    97510 : Move('white', 'f2', None, 'place', None, None, 'vertical'),
    97511 : Move('black', 'f2', None, 'place', None, None, 'vertical'),
    97600 : Move('white', 'g2', None, 'place', None, None, 'horizontal'),
    97601 : Move('black', 'g2', None, 'place', None, None, 'horizontal'),
    97610 : Move('white', 'g2', None, 'place', None, None, 'vertical'),
    97611 : Move('black', 'g2', None, 'place', None, None, 'vertical'),
    97700 : Move('white', 'h2', None, 'place', None, None, 'horizontal'),
    97701 : Move('black', 'h2', None, 'place', None, None, 'horizontal'),
    97710 : Move('white', 'h2', None, 'place', None, None, 'vertical'),
    97711 : Move('black', 'h2', None, 'place', None, None, 'vertical'),
    97800 : Move('white', 'i2', None, 'place', None, None, 'horizontal'),
    97801 : Move('black', 'i2', None, 'place', None, None, 'horizontal'),
    97810 : Move('white', 'i2', None, 'place', None, None, 'vertical'),
    97811 : Move('black', 'i2', None, 'place', None, None, 'vertical'),
    98000 : Move('white', 'a1', None, 'place', None, None, 'horizontal'),
    98001 : Move('black', 'a1', None, 'place', None, None, 'horizontal'),
    98010 : Move('white', 'a1', None, 'place', None, None, 'vertical'),
    98011 : Move('black', 'a1', None, 'place', None, None, 'vertical'),
    98100 : Move('white', 'b1', None, 'place', None, None, 'horizontal'),
    98101 : Move('black', 'b1', None, 'place', None, None, 'horizontal'),
    98110 : Move('white', 'b1', None, 'place', None, None, 'vertical'),
    98111 : Move('black', 'b1', None, 'place', None, None, 'vertical'),
    98200 : Move('white', 'c1', None, 'place', None, None, 'horizontal'),
    98201 : Move('black', 'c1', None, 'place', None, None, 'horizontal'),
    98210 : Move('white', 'c1', None, 'place', None, None, 'vertical'),
    98211 : Move('black', 'c1', None, 'place', None, None, 'vertical'),
    98300 : Move('white', 'd1', None, 'place', None, None, 'horizontal'),
    98301 : Move('black', 'd1', None, 'place', None, None, 'horizontal'),
    98310 : Move('white', 'd1', None, 'place', None, None, 'vertical'),
    98311 : Move('black', 'd1', None, 'place', None, None, 'vertical'),
    98400 : Move('white', 'e1', None, 'place', None, None, 'horizontal'),
    98401 : Move('black', 'e1', None, 'place', None, None, 'horizontal'),
    98410 : Move('white', 'e1', None, 'place', None, None, 'vertical'),
    98411 : Move('black', 'e1', None, 'place', None, None, 'vertical'),
    98500 : Move('white', 'f1', None, 'place', None, None, 'horizontal'),
    98501 : Move('black', 'f1', None, 'place', None, None, 'horizontal'),
    98510 : Move('white', 'f1', None, 'place', None, None, 'vertical'),
    98511 : Move('black', 'f1', None, 'place', None, None, 'vertical'),
    98600 : Move('white', 'g1', None, 'place', None, None, 'horizontal'),
    98601 : Move('black', 'g1', None, 'place', None, None, 'horizontal'),
    98610 : Move('white', 'g1', None, 'place', None, None, 'vertical'),
    98611 : Move('black', 'g1', None, 'place', None, None, 'vertical'),
    98700 : Move('white', 'h1', None, 'place', None, None, 'horizontal'),
    98701 : Move('black', 'h1', None, 'place', None, None, 'horizontal'),
    98710 : Move('white', 'h1', None, 'place', None, None, 'vertical'),
    98711 : Move('black', 'h1', None, 'place', None, None, 'vertical'),
    98800 : Move('white', 'i1', None, 'place', None, None, 'horizontal'),
    98801 : Move('black', 'i1', None, 'place', None, None, 'horizontal'),
    98810 : Move('white', 'i1', None, 'place', None, None, 'vertical'),
    98811 : Move('black', 'i1', None, 'place', None, None, 'vertical'),

}

'''

code for generating the ids/codes lives here:

(O_O)¬

for i in range(9):
        for j in range(9):
            for k in range(2):
                for l in range(2):
                    if k == 0:
                        #def Move(self, colour, start, end, action, direction, jumpDirection=None, orientation=None):
                        orientation = 'horizontal'
                        colour = 'white' if l == 0 else 'black'
                        position = moveNumberToLetter(j) + str(9 - i)
                        print(f"9{i}{j}{k}{l} : Move('{colour}', '{position}', {None}, 'place', {None}, {None}, '{orientation}'),")
                    else:
                        orientation = 'vertical'
                        colour = 'white' if l == 0 else 'black'
                        position = moveNumberToLetter(j) + str(9 - i)
                        print(f"9{i}{j}{k}{l} : Move('{colour}', '{position}', {None}, 'place', {None}, {None}, '{orientation}'),")

'''